#!/usr/bin/env node
/**
 * App Promo Studio — Render Engine v2
 *
 * Pipeline per scene:
 *   1. Create blurred background (fills 1920×1080) from source image
 *   2. Overlay sharp version (scaled to fit)
 *   3. Apply Ken Burns zoom/pan effect
 *   4. Overlay text PNG (generated by gen_overlays.py) with fade
 *
 * Then concatenate all scenes with xfade transitions.
 *
 * Usage:
 *   node render.mjs [--storyboard storyboard.json] [--output output/promo.mp4]
 */

import { execFileSync } from 'child_process';
import { readFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Args ───
const args = process.argv.slice(2);
const storyboardPath = getArg(args, '--storyboard', join(__dirname, 'storyboard.json'));
const outputPath = getArg(args, '--output', join(__dirname, 'output', 'promo.mp4'));
const keepIntermediates = args.includes('--keep-intermediates');

// ─── Load storyboard ───
if (!existsSync(storyboardPath)) {
  console.error(`❌ Storyboard not found: ${storyboardPath}`);
  process.exit(1);
}
const sb = JSON.parse(readFileSync(storyboardPath, 'utf8'));

const W = sb.resolution.width;
const H = sb.resolution.height;
const FPS = sb.fps || 30;
const OVERLAY_DIR = join(__dirname, 'output', '.overlays');

console.log(`\n🎬 App Promo Studio — Render Engine v2`);
console.log(`   Project: ${sb.project}`);
console.log(`   Output: ${W}×${H} @ ${FPS}fps`);
console.log(`   Scenes: ${sb.scenes.length}`);

// ─── Helpers ───
function run(cmd, cmdArgs, label) {
  const start = Date.now();
  console.log(`\n   ▸ ${label}...`);
  try {
    const stdout = execFileSync(cmd, cmdArgs, {
      stdio: ['pipe', 'pipe', 'pipe'],
      maxBuffer: 10 * 1024 * 1024
    });
    const ms = Date.now() - start;
    console.log(`   ✓ Done (${(ms / 1000).toFixed(1)}s)`);
    return stdout;
  } catch (e) {
    console.error(`   ❌ FAILED: ${label}`);
    console.error(e.stderr?.toString()?.split('\n')?.slice(-5)?.join('\n') || e.message);
    throw e;
  }
}

/**
 * Render a single scene to MP4.
 */
function renderScene(scene, index, tempDir) {
  const imgPath = resolve(__dirname, scene.image);
  const overlayPath = join(OVERLAY_DIR, `overlay_${String(index).padStart(2, '0')}.png`);
  const outPath = join(tempDir, `scene_${String(index).padStart(2, '0')}.mp4`);
  const totalFrames = Math.floor(scene.duration * FPS);

  if (!existsSync(imgPath)) {
    throw new Error(`Scene image not found: ${imgPath}`);
  }

  const zoomFrom = scene.zoom_from || 1.0;
  const zoomTo = scene.zoom_to || 1.2;

  // ─── zoompan expressions ───
  const zoomExpr = `'${zoomFrom}+(${zoomTo}-${zoomFrom})*on/${totalFrames}'`;

  let xExpr, yExpr;
  switch (scene.animation) {
    case 'zoom_in_center':
      xExpr = `'(iw-iw*zoom)/2'`;
      yExpr = `'(ih-ih*zoom)/2'`;
      break;
    case 'pan_right_zoom':
      xExpr = `'(iw-iw*zoom)*on/${totalFrames}'`;
      yExpr = `'(ih-ih*zoom)/2'`;
      break;
    case 'zoom_to_detail':
      xExpr = `'(iw-iw*zoom)/2'`;
      yExpr = `'(ih-ih*zoom)*0.3'`;
      break;
    case 'pan_down':
      xExpr = `'(iw-iw*zoom)/2'`;
      yExpr = `'(ih-ih*zoom)*on/${totalFrames}'`;
      break;
    case 'zoom_out':
      xExpr = `'(iw-iw*zoom)/2'`;
      yExpr = `'(ih-ih*zoom)/2'`;
      break;
    case 'fade_out_zoom':
      xExpr = `'(iw-iw*zoom)/2'`;
      yExpr = `'(ih-ih*zoom)/2'`;
      break;
    default:
      xExpr = `'(iw-iw*zoom)/2'`;
      yExpr = `'(ih-ih*zoom)/2'`;
  }

  // ─── Build filter_complex ───
  const filters = [];

  // Input 0: source image, Input 1: text overlay PNG (optional)
  const hasOverlay = existsSync(overlayPath);

  // Split source into bg + fg
  filters.push('[0:v]split=2[bg_src][fg_src]');

  // Background: scale to fill, heavy blur
  filters.push(
    `[bg_src]scale=${W}:${H}:force_original_aspect_ratio=increase,` +
    `crop=${W}:${H},` +
    `gblur=sigma=30,` +
    `setsar=1[bg]`
  );

  // Foreground: scale to fit (contain), pad centered on black
  filters.push(
    `[fg_src]scale=${W}:${H}:force_original_aspect_ratio=decrease,` +
    `pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2:color=black,` +
    `setsar=1[fg_padded]`
  );

  // Composite fg over bg
  filters.push('[bg][fg_padded]overlay=0:0[composite]');

  // zoompan
  filters.push(
    `[composite]zoompan=` +
    `z=${zoomExpr}:` +
    `x=${xExpr}:` +
    `y=${yExpr}:` +
    `d=${totalFrames}:` +
    `s=${W}x${H}:` +
    `fps=${FPS},` +
    `format=yuva420p,` +
    `setsar=1[zoomed]`
  );

  // Text overlay with fade in/out
  let finalLabel = 'zoomed';
  if (hasOverlay) {
    const fadeInSec = 0.5;
    const fadeOutSec = 0.5;
    const fadeOutStart = scene.duration - fadeOutSec;

    // Input 1 is the overlay PNG
    filters.push(
      `[1:v]format=rgba,` +
      `fade=t=in:st=0:d=${fadeInSec}:alpha=1,` +
      `fade=t=out:st=${fadeOutStart}:d=${fadeOutSec}:alpha=1[overlay_faded]`
    );

    // Overlay text on zoomed video
    filters.push(
      `[zoomed][overlay_faded]overlay=0:0:format=auto[with_text]`
    );
    finalLabel = 'with_text';
  }

  // Scene-level fade to/from black (for smooth transitions)
  // First scene fades in, last scene fades out
  let sceneFadeIn = 0;
  let sceneFadeOut = 0;
  if (index === 0) sceneFadeIn = 0.5;
  if (index === sb.scenes.length - 1) sceneFadeOut = 0.5;

  if (sceneFadeIn > 0 || sceneFadeOut > 0) {
    const fadeParts = [];
    if (sceneFadeIn > 0) {
      fadeParts.push(`fade=t=in:st=0:d=${sceneFadeIn}`);
    }
    if (sceneFadeOut > 0) {
      fadeParts.push(`fade=t=out:st=${scene.duration - sceneFadeOut}:d=${sceneFadeOut}`);
    }
    filters.push(`[${finalLabel}]${fadeParts.join(',')}[faded]`);
    finalLabel = 'faded';
  }

  const filterComplex = filters.join(';\n  ');

  // ─── Build ffmpeg args ───
  const ffArgs = [
    '-y',
    '-loop', '1', '-i', imgPath,
  ];

  if (hasOverlay) {
    ffArgs.push('-loop', '1', '-i', overlayPath);
  }

  ffArgs.push(
    '-filter_complex', filterComplex,
    '-map', `[${finalLabel}]`,
    '-t', String(scene.duration),
    '-r', String(FPS),
    '-c:v', 'libx264',
    '-preset', 'medium',
    '-crf', '18',
    '-pix_fmt', 'yuv420p',
    '-movflags', '+faststart',
    outPath
  );

  run('ffmpeg', ffArgs, `Scene ${index + 1}/${sb.scenes.length}: "${scene.title || scene.id}"`);
  return outPath;
}

/**
 * Concatenate scenes with xfade transitions.
 */
function concatWithTransitions(scenePaths, outputPath, transitionDuration = 0.5) {
  if (scenePaths.length === 1) {
    run('ffmpeg', ['-y', '-i', scenePaths[0], '-c', 'copy', outputPath], 'Single scene → final');
    return;
  }

  const inputs = [];
  for (const p of scenePaths) {
    inputs.push('-i', p);
  }

  // Build xfade chain: [0:v]⊕[1:v]→[x1], [x1]⊕[2:v]→[x2], ...
  //
  // xfade offset is relative to the FIRST input's timeline.
  // After each xfade, the output duration = inputA_dur + inputB_dur - transition_dur.
  // So we track the accumulated output duration.
  const xfadeFilters = [];
  let prev = '[0:v]';
  let accumDur = sb.scenes[0].duration; // duration of [0:v]

  for (let i = 1; i < scenePaths.length; i++) {
    // Transition starts at: accumDur - transitionDuration
    const offset = accumDur - transitionDuration;
    const outLbl = i === scenePaths.length - 1 ? '[vout]' : `[x${i}]`;

    xfadeFilters.push(
      `${prev}[${i}:v]xfade=transition=fade:duration=${transitionDuration}:offset=${offset.toFixed(3)}${outLbl}`
    );

    // Update accumulated duration: prev_output + this_scene - transition
    accumDur = accumDur + sb.scenes[i].duration - transitionDuration;
    prev = outLbl;
  }

  const ffArgs = [
    '-y',
    ...inputs,
    '-filter_complex', xfadeFilters.join(';'),
    '-map', '[vout]',
    '-r', String(FPS),
    '-c:v', 'libx264',
    '-preset', 'medium',
    '-crf', '18',
    '-pix_fmt', 'yuv420p',
    '-movflags', '+faststart',
    outputPath
  ];

  run('ffmpeg', ffArgs, `Concatenating ${scenePaths.length} scenes with xfade transitions`);
}

// ─── Main ───
console.log('\n📦 Rendering scenes...');
mkdirSync(join(__dirname, 'output'), { recursive: true });
const tempDir = join(__dirname, 'output', '.tmp');
mkdirSync(tempDir, { recursive: true });

const scenePaths = [];
for (let i = 0; i < sb.scenes.length; i++) {
  const path = renderScene(sb.scenes[i], i, tempDir);
  scenePaths.push(path);
}

console.log('\n🔗 Assembling final video...');
concatWithTransitions(scenePaths, outputPath, 0.5);

// ─── Cleanup ───
if (!keepIntermediates) {
  const { rmSync } = await import('fs');
  rmSync(tempDir, { recursive: true, force: true });
  console.log('   ✓ Cleaned up intermediate files');
}

// ─── Report ───
const totalDur = sb.scenes.reduce((s, sc) => s + sc.duration, 0);
const transitionsTime = (sb.scenes.length - 1) * 0.5;
const finalDur = totalDur - transitionsTime;

console.log(`\n✅ Video rendered: ${outputPath}`);
console.log(`   Duration: ~${finalDur.toFixed(1)}s (${totalDur}s scenes - ${transitionsTime}s transitions)`);
console.log(`   Resolution: ${W}×${H} @ ${FPS}fps`);
console.log('');

function getArg(args, flag, fallback) {
  const idx = args.indexOf(flag);
  if (idx !== -1 && args[idx + 1]) return args[idx + 1];
  return fallback;
}
